language: java
jdk:
    - oraclejdk8
services:
    - mysql
before_script:
    - mysql -u root -e 'create database lovelive_game_db;'
    - mysql -u root lovelive_game_db < init_test_database.sql
after_success:
    - gradle jacocoTestReport coveralls
env:
  global:
    - secure: "ctBRed6KwVC+CPXWi7TSIeuTc61/510Z9KkJnJymVanqfTnMQvhQxlAHHgIxJyRAd5H6yFBi/OwMFGPzWwlD4NaJKsauWXIKo5VGeN3yXxxRjXeZK7SP9Phuy2DBdchgOXxac36GbKld2GHlOUOL29btWgtPKG7OdkuzPiSOb2GUb2BfX4dGV36A+M0UHEq88BlAZNoKa9f98KBh6Yupspx9Dae3Ikg1SOWDL/X2p7vx5Z1L70mLqnNNkU/6A8jsrHzIkzsMjX7l8eqhJnVmqkd6HRzVCgAGqmRAp7zeEs9pnnndSiUKsJ3iwIlcorsfJJsHtn0Lz3h/vOTkH5RRH+Ed5cemStx/lxesro7GP9n4imMIcVhW/C1No934mLx0dHbwPmLov6xfOO4XJfU82cPSIxu/BexWc2Pa31KWkGSxNq2kxRL/aX7FELXXYok+XwLrQzkpKui5cENikPPXHZwCeBefI+wGuVNDa9ngAUMLafGZjtwzDqy12VSCJgoNrD+baV5rZq1T7gaqH8PU98BUeNy9ztmf0H5UcwuHJrYzGMr9o7HBrCP4aCJink78n249VC5PClt40za9qhMcBlUh3xdDiPAxMeiRqOIeuZze/W92uE/v+uvbxt4Pwnp96bg4/tS3signrUUNxfVKNQJlIJ5aOAnKHpgI7pCcYx0="