language: java
jdk:
    - oraclejdk8
services:
    - mysql
before_script:
    - mysql -u root < .testDB.sql
after_success:
    - mvn clean test jacoco:report coveralls:report
env:
    global:
        secure: "D2B2NAmrVvpM+eydDdq8JlSfxX/0WhlevKLVTb3PWD1zWVGDbfMd00MHnoFNo9ZfchbfFKTA9Uwohl/jNdPXAzJJ7bEv32fdik9k6chV/NJDK+OBjvQDhS7iq/Na8BL1Dng0MCpJ5ktLEyXHmSdoGR3pCBs0mPdiUsTNAOwex/PoRJMM7fCBBFUzJQxwdfZcfA4oFLtDHBXxN9Wg36kt9MsQSKcbMTBLrhzNpn4PEMxqqDNAWNfSD1nuNqUviV5GgJ0XRAVm8NMOawQ3lfIuZu6UihDanmDMhYvgIk4SUaFZHFQhI0RYLrm4V7D37IP5fzvq50fez/eEgi0ljaN9TJwUfXNeMpqw2pLHs77RZlRMxbtHOdgIxphZwxU5SWucjZYYO2flWrmogYNugaFAFvcFCaaqgntiTJ8IvEoUKfwgef4wBpM+BbgxEn4nMy7MSrGQLynkE+tlF1u7PpWc0lYjlrvo7KJ7P3IlMoWpi1bjnycHZ2/KcnZ+C93S0fxOLLUCwJsVK/fPdzBVY0fKfrR57flFUaCi2TLnWxcbzsPL6fYIbZT1Jjb1ITU+5FrHJz5lZupKOyhOihHJPJ0Yo4IWqXKbGsq7rJkEuAU3JO1RRaXSBdOQDK64WBVs+Pu+Vyd7uDdIyifB3i/YszEdbcBJTGeHLoMj3/PdxaYkdTI="

notifications:
    slack: 
        secure: "prpgw5a7xbMLl6Vm6ZacdiYvqSg3Wl9Wv5GV+mHfJbgRZLbEl30gw3eA+ECq9R71DpB64o72ojTPChLu+jHASTqNns2I6mP6ji3gZY8p+hAl3dxX+q7mDfse6eObJ0XAI0VOevCI5Fxcj7IVPJSCmHgGQre+sILCDtl3npTXGB3swVXPlAHRDuLckt/pLEU4F8UNde5y/hj0WaHORhLAukJkacCWtq/lBeENHzz6hRuKnX0j6fxLQhW/pZDPSvHfaoLLfONzzeg8o9Q4cPzWdxQwIL2AjzkYSH3jEoUrR5RDZC6W/L6i8FuQLGCHEuxgzELrppeoLZTdTXMhDZv64uu881UnwuPAJ0hlTZPP3iXBpMMCvgnk9oNlocLyojGiaJEriYKc6bhsA+0hbaQhVcOh91Z8Yh2iCv9u5yi7M9UFILz1RrnFicePQgfHF3duz/bjCWcxscvpJniDI1m2EI6K+3NfrbMXuLCG6Kicya1w+EFHRAwMFQ4dv+1rCV8l9CAVR6zbpWYeOT9nTQNXTq3fWD2wdFLMGhvxNID4tNzZ+riZZoLlUZ306Ag/rLD1Q6HyfEhj5GUJhXQyLV7TBs1dEYoyvvb+3YNdCdYSTKQzF+HkgI16NCYh1b5mkenwaTrUXh8D2N8tcuBOqd8d8sc/zTqgvjmukRxv4N95lhY="
