language: java
jdk:
    - oraclejdk8
services:
    - mysql
before_script:
    - mysql -u root -e 'create database lovelive_game_db;'
    - mysql -u root lovelive_game_db < init_test_database.sql
after_success:
    - gradle jacocoTestReport coveralls