language: java
jdk:
    - oraclejdk8
services:
    - mysql
before_script:
    - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS LOVELIVE_GAME_DB'
after_success:
    - mvn clean test jacoco:report coveralls:report